export interface CityData {
  slug: string;
  name: string;
  county: string;
  nearbyAreas: string;
  heroImage: string;
  intro: string;
  whyTurf: string;
  contentImage: string;
  localFocus: string;
}

export const CITIES: CityData[] = [
  {
    slug: 'redlands',
    name: 'Redlands',
    county: 'San Bernardino County',
    nearbyAreas: 'Loma Linda, Highland, and Yucaipa',
    heroImage: '/images/residential-header.jpg',
    contentImage: '/images/residential-front-yard-corner-lot-01.jpg',
    intro: 'Redlands is known for its historic charm, tree-lined streets, and warm climate. Homeowners and businesses in Redlands are discovering how artificial turf can enhance their properties while saving water and eliminating the hassle of traditional lawn care.',
    whyTurf: 'With Redlands\' hot, dry summers and water conservation priorities, artificial turf is the smart choice. Keep your yard green and beautiful year-round without the constant watering, mowing, and fertilizing that natural grass demands.',
    localFocus: 'From the historic districts near downtown Redlands to newer developments in East Redlands, we tailor our installations to complement every style of property. Our team understands the local landscape and HOA requirements throughout the area.',
  },
  {
    slug: 'highland',
    name: 'Highland',
    county: 'San Bernardino County',
    nearbyAreas: 'San Bernardino, Redlands, and Loma Linda',
    heroImage: '/images/home-header-turf.jpg',
    contentImage: '/images/residential-backyard-palm-trees-lights-05.jpg',
    intro: 'Highland is our home base, and we take special pride in serving our local community. From family homes to commercial properties along Base Line and Highland Avenue, we deliver premium turf installations that stand the test of time.',
    whyTurf: 'Highland\'s climate is perfect for artificial turf — hot summers mean high water bills for natural grass. Switch to synthetic turf and enjoy a lush, green lawn every day of the year while saving hundreds on your water bill.',
    localFocus: 'As Highland locals ourselves, we know the neighborhoods, the soil conditions, and the unique needs of properties in this area. From East Highland Ranch to the communities near Highland Avenue, we\'ve installed turf across every part of town.',
  },
  {
    slug: 'san-bernardino',
    name: 'San Bernardino',
    county: 'San Bernardino County',
    nearbyAreas: 'Highland, Loma Linda, and Colton',
    heroImage: '/images/commercial-header.jpg',
    contentImage: '/images/commercial-building-turf-lawn-01.jpg',
    intro: 'San Bernardino is a growing city with a diverse mix of residential neighborhoods and commercial districts. Precision Turf Works helps property owners across San Bernardino create beautiful, low-maintenance landscapes that thrive in the Inland Empire heat.',
    whyTurf: 'San Bernardino\'s dry climate and water restrictions make artificial turf the practical and beautiful choice. Reduce your water usage dramatically while maintaining a professional, green appearance for your home or business.',
    localFocus: 'From residential yards in the Verdemont and North Park neighborhoods to commercial properties along Hospitality Lane, we serve every corner of San Bernardino with the same commitment to quality and craftsmanship.',
  },
  {
    slug: 'yucaipa',
    name: 'Yucaipa',
    county: 'San Bernardino County',
    nearbyAreas: 'Redlands, Calimesa, and Beaumont',
    heroImage: '/images/residential-hilltop-pool-mountain-view-21.jpg',
    contentImage: '/images/residential-backyard-roses-hillside-16.jpg',
    intro: 'Yucaipa\'s small-town feel and family-friendly neighborhoods make it a wonderful place to live. Our artificial turf installations help Yucaipa homeowners spend less time on yard work and more time enjoying their outdoor spaces.',
    whyTurf: 'Yucaipa\'s warm climate and semi-rural character mean many homeowners have larger yards that require significant upkeep. Artificial turf eliminates the endless cycle of mowing, watering, and weeding, giving you a pristine lawn with minimal effort.',
    localFocus: 'Whether your property is in the foothills near Oak Glen Road or in established neighborhoods throughout Yucaipa, our installations are designed to complement the natural beauty of the area while providing a durable, long-lasting surface.',
  },
  {
    slug: 'beaumont',
    name: 'Beaumont',
    county: 'Riverside County',
    nearbyAreas: 'Banning, Calimesa, and Cherry Valley',
    heroImage: '/images/golf-header.jpg',
    contentImage: '/images/residential-backyard-stepping-stones-pool-23.jpg',
    intro: 'Beaumont is one of the Inland Empire\'s fastest-growing communities, with new developments and established neighborhoods alike. Precision Turf Works brings premium artificial turf solutions to Beaumont homeowners looking for beautiful, hassle-free landscapes.',
    whyTurf: 'Beaumont\'s location in the San Gorgonio Pass means wind, heat, and dry conditions that can make maintaining natural grass a constant battle. Artificial turf stays perfect through wind, heat, and drought — no brown patches, no dead spots.',
    localFocus: 'From the master-planned communities at Fairway Canyon and Tournament Hills to established areas throughout Beaumont, we install turf that enhances property value and curb appeal in every neighborhood.',
  },
  {
    slug: 'loma-linda',
    name: 'Loma Linda',
    county: 'San Bernardino County',
    nearbyAreas: 'Redlands, San Bernardino, and Highland',
    heroImage: '/images/residential-backyard-patio-fire-pit-19.jpg',
    contentImage: '/images/residential-backyard-dog-on-turf-07.jpg',
    intro: 'Loma Linda is a health-conscious community known for its university, medical center, and family-oriented neighborhoods. Our artificial turf installations provide safe, chemical-free outdoor spaces that align with Loma Linda\'s wellness-focused lifestyle.',
    whyTurf: 'No pesticides, no fertilizers, no gas-powered mowing — artificial turf aligns perfectly with Loma Linda\'s commitment to healthy living. Create a beautiful outdoor space that\'s safe for children and pets without harmful chemicals.',
    localFocus: 'From the homes surrounding Loma Linda University Medical Center to residential neighborhoods throughout the city, our team provides professional installations tailored to each property\'s unique needs and character.',
  },
  {
    slug: 'riverside',
    name: 'Riverside',
    county: 'Riverside County',
    nearbyAreas: 'Moreno Valley, Corona, and Norco',
    heroImage: '/images/commercial-courtyard-wide-view-04.jpg',
    contentImage: '/images/commercial-courtyard-drainage-palms-02.jpg',
    intro: 'Riverside is the heart of the Inland Empire, with a rich history and thriving community. From the Mission Inn district to suburban neighborhoods, Precision Turf Works helps Riverside residents and businesses create stunning, low-maintenance landscapes.',
    whyTurf: 'Riverside\'s hot summers and periodic drought restrictions make water-wise landscaping essential. Artificial turf gives you a beautiful green space year-round while drastically reducing your water consumption.',
    localFocus: 'We serve all areas of Riverside — from the historic neighborhoods near downtown to the Canyon Crest, La Sierra, and Arlington communities. Commercial properties along University Avenue and the Magnolia district trust our professional installations.',
  },
  {
    slug: 'rancho-cucamonga',
    name: 'Rancho Cucamonga',
    county: 'San Bernardino County',
    nearbyAreas: 'Ontario, Upland, and Fontana',
    heroImage: '/images/showcase-luxury-turf-courtyard.jpg',
    contentImage: '/images/residential-modern-pool-wood-deck-22.jpg',
    intro: 'Rancho Cucamonga is known for its master-planned communities, excellent schools, and high standards of curb appeal. Our premium artificial turf installations help Rancho Cucamonga homeowners maintain picture-perfect yards without the constant maintenance.',
    whyTurf: 'Many Rancho Cucamonga neighborhoods have HOA standards that demand well-maintained lawns. Artificial turf delivers consistent, flawless curb appeal every single day — no brown spots, no bare patches, no seasonal die-off.',
    localFocus: 'From the upscale communities of Etiwanda and Terra Vista to homes near Victoria Gardens and the foothills, we provide turf installations that meet the high standards Rancho Cucamonga residents expect.',
  },
  {
    slug: 'colton',
    name: 'Colton',
    county: 'San Bernardino County',
    nearbyAreas: 'San Bernardino, Loma Linda, and Grand Terrace',
    heroImage: '/images/residential-backyard-vinyl-fence-trees-13.jpg',
    contentImage: '/images/residential-front-yard-walkway-02.jpg',
    intro: 'Colton is a historic community in the heart of the Inland Empire. Our artificial turf solutions help Colton homeowners and businesses create attractive, durable outdoor spaces that withstand the demands of the local climate.',
    whyTurf: 'Colton\'s warm climate and affordable housing make it a great place to invest in your property. Artificial turf adds instant curb appeal and value while eliminating the cost and hassle of traditional lawn maintenance.',
    localFocus: 'From residential neighborhoods near Colton High School to commercial properties along Valley Boulevard, we bring the same professional quality and attention to detail to every Colton installation.',
  },
  {
    slug: 'ontario',
    name: 'Ontario',
    county: 'San Bernardino County',
    nearbyAreas: 'Rancho Cucamonga, Upland, and Montclair',
    heroImage: '/images/commercial-glass-facade-turf-03.jpg',
    contentImage: '/images/commercial-apartment-courtyard-pool-07.jpg',
    intro: 'Ontario is a dynamic city with a growing mix of residential communities and commercial centers. Precision Turf Works provides Ontario property owners with premium artificial turf that looks great and performs even better.',
    whyTurf: 'Ontario\'s blend of residential and commercial properties makes artificial turf a versatile solution. From backyard lawns to corporate landscaping, synthetic turf delivers a professional appearance with zero irrigation costs.',
    localFocus: 'We serve Ontario\'s diverse neighborhoods — from the Ontario Ranch master-planned community to historic areas near Euclid Avenue, as well as commercial properties around Ontario International Airport and the Ontario Mills area.',
  },
  {
    slug: 'palm-springs',
    name: 'Palm Springs',
    county: 'Riverside County',
    nearbyAreas: 'Cathedral City, Rancho Mirage, and Palm Desert',
    heroImage: '/images/putting-green-poolside-palms-04.jpg',
    contentImage: '/images/putting-green-pool-spa-ranch-09.jpg',
    intro: 'Palm Springs is synonymous with desert luxury and modernist style. Our artificial turf installations bring lush green spaces to this iconic desert city, creating stunning outdoor living areas that complement the Palm Springs aesthetic.',
    whyTurf: 'In Palm Springs\' desert climate, maintaining natural grass is extremely costly and water-intensive. Artificial turf delivers the lush look of a resort lawn while respecting the desert environment and keeping water bills manageable.',
    localFocus: 'From mid-century modern homes in the Movie Colony to vacation properties in Las Palmas, and from boutique hotels along Palm Canyon Drive to residential communities throughout Palm Springs, our installations enhance the desert lifestyle.',
  },
  {
    slug: 'palm-desert',
    name: 'Palm Desert',
    county: 'Riverside County',
    nearbyAreas: 'Indian Wells, Rancho Mirage, and La Quinta',
    heroImage: '/images/putting-green-ranch-house-pool-06.jpg',
    contentImage: '/images/putting-green-modern-guesthouse-12.jpg',
    intro: 'Palm Desert offers resort-style living in the Coachella Valley. Our artificial turf and putting green installations help Palm Desert homeowners create beautiful outdoor spaces that thrive in the desert heat without wasting precious water.',
    whyTurf: 'Palm Desert residents know that water conservation is a way of life. Artificial turf provides a vibrant, green landscape without the enormous water bills that come with maintaining natural grass in the desert climate.',
    localFocus: 'From the fairway homes at Desert Willow to estates on El Paseo, and from commercial properties along Monterey Avenue to communities near The Living Desert, our turf solutions are designed for the unique demands of Palm Desert properties.',
  },
  {
    slug: 'corona',
    name: 'Corona',
    county: 'Riverside County',
    nearbyAreas: 'Riverside, Norco, and Eastvale',
    heroImage: '/images/residential-backyard-palm-shadows-pool-08.jpg',
    contentImage: '/images/residential-backyard-patio-dining-12.jpg',
    intro: 'Corona\'s family-friendly neighborhoods and growing community make it one of the Inland Empire\'s most desirable cities. Our artificial turf installations help Corona homeowners enjoy beautiful yards that are perfect for kids, pets, and entertaining.',
    whyTurf: 'Corona\'s warm climate and active family lifestyles mean yards get heavy use. Artificial turf stands up to the wear and tear of daily life — no bare patches from the dog, no mud tracked inside after rain, and no weekend mowing.',
    localFocus: 'From the hilltop communities of Sierra Del Oro to the neighborhoods near Corona Heritage Park, and from commercial properties along the 91 corridor to residential streets throughout the city, we deliver professional results in every part of Corona.',
  },
  {
    slug: 'moreno-valley',
    name: 'Moreno Valley',
    county: 'Riverside County',
    nearbyAreas: 'Riverside, Perris, and Beaumont',
    heroImage: '/images/residential-front-yard-palms-street-view-10.jpg',
    contentImage: '/images/residential-backyard-flagstone-bamboo-18.jpg',
    intro: 'Moreno Valley is a vibrant, growing community in Riverside County. Our artificial turf solutions help Moreno Valley homeowners and businesses transform their outdoor spaces into beautiful, low-maintenance landscapes.',
    whyTurf: 'Moreno Valley\'s hot summers and dry conditions can make lawn maintenance exhausting and expensive. Artificial turf eliminates the struggle, giving you a perfect lawn that never needs watering, mowing, or chemical treatments.',
    localFocus: 'From the master-planned communities in the eastern hills to established neighborhoods near March Air Reserve Base and the Towngate area, our team provides quality turf installations throughout Moreno Valley.',
  },
  {
    slug: 'menifee',
    name: 'Menifee',
    county: 'Riverside County',
    nearbyAreas: 'Murrieta, Temecula, and Lake Elsinore',
    heroImage: '/images/residential-front-yard-curved-edging-04.jpg',
    contentImage: '/images/residential-backyard-fence-line-14.jpg',
    intro: 'Menifee is one of the fastest-growing cities in Southern California, with new developments and family-oriented communities. Precision Turf Works helps Menifee homeowners create beautiful, hassle-free landscapes from day one.',
    whyTurf: 'Many new Menifee homes have smaller yards that benefit greatly from artificial turf — maximum beauty with minimum effort. And for larger lots, turf eliminates the high water bills and constant upkeep that come with natural grass.',
    localFocus: 'From the Audie Murphy Ranch and Heritage Lake communities to established neighborhoods throughout Menifee, we install premium turf that meets the standards of this growing, family-focused city.',
  },
  {
    slug: 'murrieta',
    name: 'Murrieta',
    county: 'Riverside County',
    nearbyAreas: 'Temecula, Menifee, and Wildomar',
    heroImage: '/images/residential-backyard-stepping-stones-swing-09.jpg',
    contentImage: '/images/residential-front-yard-river-rock-border-17.jpg',
    intro: 'Murrieta consistently ranks as one of the safest and most desirable cities in California. Our artificial turf installations help Murrieta families enjoy pristine outdoor spaces that are safe for kids and pets while enhancing property value.',
    whyTurf: 'Murrieta homeowners take pride in their properties, and many HOAs require well-maintained landscaping. Artificial turf delivers perfect curb appeal 365 days a year, without the water waste, chemical treatments, or weekend yard work.',
    localFocus: 'From the Greer Ranch and Vista Murrieta communities to homes near Murrieta Hot Springs and the Town Center, our team provides expert installations that complement the high standards of Murrieta\'s neighborhoods.',
  },
  {
    slug: 'temecula',
    name: 'Temecula',
    county: 'Riverside County',
    nearbyAreas: 'Murrieta, Fallbrook, and Lake Elsinore',
    heroImage: '/images/putting-green-kidney-shape-pool-03.jpg',
    contentImage: '/images/putting-green-four-flags-rock-border-01.jpg',
    intro: 'Temecula is famous for its wine country, Old Town charm, and beautiful communities. Precision Turf Works brings premium artificial turf to Temecula homeowners who want resort-quality landscapes without the resort-level maintenance.',
    whyTurf: 'Temecula\'s warm, Mediterranean-like climate is ideal for outdoor living. Artificial turf extends your usable outdoor space and keeps it looking immaculate for pool parties, barbecues, and everyday family life.',
    localFocus: 'From the estates of Redhawk and Wolf Creek to homes near Old Town Temecula and the wine country, we provide turf solutions that enhance the distinctive character of every Temecula neighborhood.',
  },
  {
    slug: 'lake-elsinore',
    name: 'Lake Elsinore',
    county: 'Riverside County',
    nearbyAreas: 'Wildomar, Menifee, and Canyon Lake',
    heroImage: '/images/residential-hilltop-patio-valley-view-20.jpg',
    contentImage: '/images/residential-pool-lounge-mountain-view-24.jpg',
    intro: 'Lake Elsinore offers stunning lakeside living and a growing community of families and outdoor enthusiasts. Our artificial turf installations help Lake Elsinore homeowners create beautiful yards that complement the area\'s natural beauty.',
    whyTurf: 'Lake Elsinore\'s hot summers and active outdoor lifestyle call for durable, low-maintenance landscaping. Artificial turf gives you a green, ready-to-use yard that\'s perfect for family fun without the constant upkeep.',
    localFocus: 'From the Rosetta Canyon community to neighborhoods near the lake and throughout Canyon Hills, our team delivers professional turf installations designed for the unique terrain and climate of Lake Elsinore.',
  },
  {
    slug: 'norco',
    name: 'Norco',
    county: 'Riverside County',
    nearbyAreas: 'Corona, Riverside, and Eastvale',
    heroImage: '/images/residential-backyard-aerial-layout-15.jpg',
    contentImage: '/images/residential-side-yard-shade-trees-11.jpg',
    intro: 'Known as "Horse Town USA," Norco combines rural charm with suburban convenience. Our artificial turf solutions help Norco property owners create clean, durable outdoor areas that stand up to the demands of equestrian and family life.',
    whyTurf: 'Norco\'s larger lots and active outdoor lifestyle mean more area to maintain. Artificial turf reduces the workload dramatically while providing safe, comfortable surfaces for families, pets, and outdoor activities.',
    localFocus: 'From the equestrian properties along Hamner Avenue to residential neighborhoods near Hidden Valley and throughout Norco, we customize our installations to fit the unique character and needs of each property.',
  },
  {
    slug: 'hemet',
    name: 'Hemet',
    county: 'Riverside County',
    nearbyAreas: 'San Jacinto, Beaumont, and Menifee',
    heroImage: '/images/residential-front-yard-turf-closeup-03.jpg',
    contentImage: '/images/residential-pool-area-hillside-25.jpg',
    intro: 'Hemet offers affordable living in the San Jacinto Valley with a warm, sunny climate. Precision Turf Works helps Hemet homeowners transform their yards into beautiful, low-maintenance spaces that thrive in the valley heat.',
    whyTurf: 'Hemet\'s hot summers and limited water resources make artificial turf a smart investment. Eliminate your lawn watering bill while enjoying a green, attractive yard that never wilts, browns, or needs mowing.',
    localFocus: 'From the Four Seasons community to residential areas near Hemet Valley Medical Center and throughout the city, our professional installations are designed to enhance property value and reduce maintenance for Hemet homeowners.',
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
